### ISSUE TITLE
Obscure error when failing to instantiate plugs

### ISSUE THREAD

**Issue by grybmadsci** [google/openhtf#193]
Currently, we get a stacktrace like:
```
Exception in thread TestExecutorThread:
Traceback (most recent call last):
  File "c:\python27\Lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Users\CameraLab02\venv\lib\site-packages\openhtf\util\threads.py", line 51, in run
    self._ThreadProc()
  File "C:\Users\CameraLab02\venv\lib\site-packages\openhtf\exe\__init__.py", line 109, in _ThreadProc
    self._RunTestLoop.once(self)
  File "C:\Users\CameraLab02\venv\lib\site-packages\openhtf\exe\__init__.py", line 129, in _RunTestLoop
    plug_manager = self._MakePlugManager(suppressor)
  File "C:\Users\CameraLab02\venv\lib\site-packages\openhtf\exe\__init__.py", line 148, in _MakePlugManager
    plugs.PlugManager.InitializeFromTypeMap(self.test.plug_type_map))
  File "C:\Users\CameraLab02\venv\lib\site-packages\openhtf\plugs\__init__.py", line 212, in InitializeFromTypeMap
    plug_map[plug] = plug_type()
  File "C:\Users\CameraLab02\venv\lib\site-packages\openhtf\conf.py", line 520, in SelfWrapper
    return method_wrapper(**kwargs)
  File "C:\Users\CameraLab02\venv\lib\site-packages\openhtf\conf.py", line 511, in method_wrapper
    return method(**final_kwargs)
TypeError: __init__() takes exactly 2 arguments (1 given)
```
This should be intercepted and at least print out `plug_type.__name__` or something and reraise.

**Comment by grybmadsci** [comment]
Ah, my mistake, we actually already do this, it just had scrolled off the top because that stack trace got printed a bajillion times...
