### ISSUE TITLE
AttributeError: 'NoneType' if SIGINT called before scanning serial

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#250]
python hello_world.py 

Provide a DUT ID in order to start the test.
^C2016-05-17 11:54:41,791 - ERROR - Received SIGINT.
2016-05-17 11:54:41,792 - ERROR - Stopping Test due to SIGINT: None
Traceback (most recent call last):
  File "hello_world.py", line 87, in <module>
    test.Execute(test_start=triggers.PromptForTestStart())
  File "/home/source/openhtf/openhtf/__init__.py", line 181, in Execute
    record = self._executor.GetState().GetFinishedRecord()
AttributeError: 'NoneType' object has no attribute 'GetFinishedRecord'

**Comment by wallacbe** [comment]
finally:
      record = self._executor.GetState().GetFinishedRecord()
      self.OutputTestRecord(record)
      if http_server:
        http_server.Stop()


Is this an acceptable solution?

    finally:
      if self._executor.GetState():
        record = self._executor.GetState().GetFinishedRecord()
        self.OutputTestRecord(record)
      if http_server:
      http_server.Stop()
