### ISSUE TITLE
RuntimeError is raised when looping Execute

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#269]
I put Execute in a loop:
```
while True:
    test.Execute(test_start=triggers.PromptForTestStart())
```

Raises RuntimeError

python hello_world.py
Provide a DUT ID in order to start the test.
test
Hello World!
Finishing test execution with outcome PASS.
Traceback (most recent call last):
  File "hello_world.py", line 88, in <module>
    test.Execute(test_start=triggers.PromptForTestStart())
  File "/home/source/venv/local/lib/python2.7/site-packages/openhtf-0.9-py2.7.egg/openhtf/__init__.py", line 176, in Execute
    self._executor.Start()
  File "/home/source/venv/local/lib/python2.7/site-packages/openhtf-0.9-py2.7.egg/openhtf/exe/__init__.py", line 89, in Start
    self.start()
  File "/usr/lib/python2.7/threading.py", line 739, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once

**Comment by fahhem** [comment]
Dang, `exe.TestExecutor` is a thread that can't be started more than once.

**Comment by wallacbe** [comment]
I have an old wheel I built 4/11 that allows me to loop.   Any way we can revert back to prior method?

**Comment by grybmadsci** [comment]
Fixed, thanks farz.
