### ISSUE TITLE
Frontend Multicast Issues for OSX

### ISSUE THREAD

**Issue by kdsudac** [google/openhtf#398]
Running frontend server and test stations on OSX was casuing tracebacks in openhtf/util/multicast.py:

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/kdsudac/openhtf/openhtf/util/multicast.py", line 97, in run
    self._sock.bind(('', self.port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 48] Address already in use
```

Think it could be due to differences in Unix vs BSD and sockets: http://stackoverflow.com/questions/32661091/behavior-of-so-reuseaddr-and-so-reuseport-changed

https://github.com/robovm/robovm/commit/c6b93701c2bc1a3b417090703b5c75ec1af8b5ff

Also, from reading it seems like these options need to be set everywhere that socket is bound to.  They are being set int MulticastListener.run() but not in multicast.send().

This issue may be irrelevant after https://github.com/google/openhtf/pull/391

**Comment by fahhem** [comment]
#391 is in now, can you retry and reopen this bug if it's still a problem?
