### ISSUE TITLE
Launching Frontend throws error openhtf.util.conf.KeyAlreadyDeclaredError: ('Configuration key already declared', 'teardown_timeout_s')

### ISSUE THREAD

**Issue by csaint00** [google/openhtf#477]
Just synched to head and now receive this error when launching frontend:

python -m openhtf.output.web_gui
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 151, in _run_module_as_main
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/usr/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/usr/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/usr/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/usr/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "openhtf/__init__.py", line 41, in <module>
    from openhtf.core import history
  File "openhtf/openhtf/core/__init__.py", line 38, in <module>
    'Timeout (in seconds) for test teardown functions.')
  File "openhtf/util/threads.py", line 129, in synchronized_method
    return func(self, *args, **kwargs)
  File "openhtf/util/conf.py", line 342, in declare
    'Configuration key already declared', name)
openhtf.util.conf.KeyAlreadyDeclaredError: ('Configuration key already declared', 'teardown_timeout_s')

**Comment by csaint00** [comment]
Scratch that, forgot to re-install, issue resolved
