### ISSUE TITLE
OverflowError: int exceeds XML-RPC limits

### ISSUE THREAD

**Issue by Kenadia** [google/openhtf#526]
Been seeing this for a couple weeks now when running any test with the web GUI.

### Traceback
```
Starting openhtf web gui server on http://localhost:12000.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/Users/kschiller/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "openhtf/output/web_gui/__init__.py", line 178, in run
    self._test.wait_for_update(timeout_s=self._wait_timeout_s))
  File "openhtf/core/station_api.py", line 296, in wait_for_update
    self.test_uid, summary_dict, timeout_s)
  File "openhtf/util/xmlrpcutil.py", line 89, in _wrapper
    return method(*args)
  File "/Users/kschiller/anaconda2/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/Users/kschiller/anaconda2/lib/python2.7/xmlrpclib.py", line 1596, in __request
    allow_none=self.__allow_none)
  File "/Users/kschiller/anaconda2/lib/python2.7/xmlrpclib.py", line 1094, in dumps
    data = m.dumps(params)
  File "/Users/kschiller/anaconda2/lib/python2.7/xmlrpclib.py", line 638, in dumps
    dump(v, write)
  File "/Users/kschiller/anaconda2/lib/python2.7/xmlrpclib.py", line 660, in __dump
    f(self, value, write)
  File "/Users/kschiller/anaconda2/lib/python2.7/xmlrpclib.py", line 741, in dump_struct
    dump(v, write)
  File "/Users/kschiller/anaconda2/lib/python2.7/xmlrpclib.py", line 660, in __dump
    f(self, value, write)
  File "/Users/kschiller/anaconda2/lib/python2.7/xmlrpclib.py", line 741, in dump_struct
    dump(v, write)
  File "/Users/kschiller/anaconda2/lib/python2.7/xmlrpclib.py", line 660, in __dump
    f(self, value, write)
  File "/Users/kschiller/anaconda2/lib/python2.7/xmlrpclib.py", line 671, in dump_int
    raise OverflowError, "int exceeds XML-RPC limits"
OverflowError: int exceeds XML-RPC limits
```

### Repro
- Tab 1: `python -m openhtf.output.web_gui`
- Tab 2: `python examples/hello_world.py`
- After a couple seconds, the Station API receives RPC calls (logged in tab 2) and the OverflowError traceback appears in tab 1.

**Comment by Kenadia** [comment]
Addressed by #524 (L90 in station_api.py)
