### ISSUE TITLE
Fault: <Fault 1: "<class 'openhtf.UnrecognizedTestUidError'>:Test UID running frontend

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#547]
Able to execute testers through the front end.  Observe the following in the log:

Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/tmp/tmp.mZvONxJMQo/virtualenv/lib/python2.7/site-packages/openhtf/output/web_gui/__init__.py", line 107, in run
    self._callback()
  File "/tmp/tmp.mZvONxJMQo/virtualenv/lib/python2.7/site-packages/openhtf/util/threads.py", line 138, in synchronized_method
    return func(self, *args, **kwargs)
  File "/tmp/tmp.mZvONxJMQo/virtualenv/lib/python2.7/site-packages/openhtf/output/web_gui/__init__.py", line 153, in handle_state_update
    state = self._test.state
  File "/tmp/tmp.mZvONxJMQo/virtualenv/lib/python2.7/site-packages/openhtf/core/station_api.py", line 123, in _wrapper
    return func(*args, **kwargs)
  File "/tmp/tmp.mZvONxJMQo/virtualenv/lib/python2.7/site-packages/openhtf/core/station_api.py", line 319, in state
    self.test_uid, summary_dict and summary_dict['test_record'])
  File "/tmp/tmp.mZvONxJMQo/virtualenv/lib/python2.7/site-packages/openhtf/util/xmlrpcutil.py", line 89, in _wrapper
    return method(*args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1482, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 794, in close
    raise Fault(**self._stack[0])
Fault: <Fault 1: "<class 'openhtf.UnrecognizedTestUidError'>:Test UID 5153:1490419853737:5003b4965a104111:6763325c3eca43b4 not recognized">

**Comment by glados-verma** [comment]
Closing as stale.
