### ISSUE TITLE
Invalid mutablerecords syntax

### ISSUE THREAD

**Issue by DanLipsitt** [google/openhtf#632]
The `mutablerecords` pylint plugin appears to be broken:

``` shellsession
$ $VIRTUAL_ENV/bin/pylint openhtf/output/callbacks/console_summary.py
Traceback (most recent call last):
  File "~/.virtualenvs/openhtf-local/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "~/.virtualenvs/openhtf-local/lib/python2.7/site-packages/pylint/__init__.py", line 13, in run_pylint
    Run(sys.argv[1:])
  File "~/.virtualenvs/openhtf-local/lib/python2.7/site-packages/pylint/lint.py", line 1300, in __init__
    linter.check(args)
  File "~/.virtualenvs/openhtf-local/lib/python2.7/site-packages/pylint/lint.py", line 726, in check
    self._do_check(files_or_modules)
  File "~/.virtualenvs/openhtf-local/lib/python2.7/site-packages/pylint/lint.py", line 855, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "~/.virtualenvs/openhtf-local/lib/python2.7/site-packages/pylint/lint.py", line 934, in check_astroid_module
    walker.walk(ast_node)
  File "~/.virtualenvs/openhtf-local/lib/python2.7/site-packages/pylint/utils.py", line 973, in walk
    self.walk(child)
  File "~/.virtualenvs/openhtf-local/lib/python2.7/site-packages/pylint/utils.py", line 970, in walk
    cb(astroid)
  File "~/.virtualenvs/openhtf-local/lib/python2.7/site-packages/pylint/checkers/variables.py", line 1144, in visit_importfrom
    module = node.do_import_module(name_parts[0])
  File "~/.virtualenvs/openhtf-local/lib/python2.7/site-packages/astroid/mixins.py", line 119, in do_import_module
    relative_only=level and level >= 1)
  File "~/.virtualenvs/openhtf-local/lib/python2.7/site-packages/astroid/scoped_nodes.py", line 415, in import_module
    return MANAGER.ast_from_module_name(modname)
  File "~/.virtualenvs/openhtf-local/lib/python2.7/site-packages/astroid/manager.py", line 154, in ast_from_module_name
    return self.ast_from_file(found_spec.location, modname, fallback=False)
  File "~/.virtualenvs/openhtf-local/lib/python2.7/site-packages/astroid/manager.py", line 80, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "~/.virtualenvs/openhtf-local/lib/python2.7/site-packages/astroid/builder.py", line 152, in file_build
    return self._post_build(module, encoding)
  File "~/.virtualenvs/openhtf-local/lib/python2.7/site-packages/astroid/builder.py", line 176, in _post_build
    module = self._manager.visit_transforms(module)
  File "~/.virtualenvs/openhtf-local/lib/python2.7/site-packages/astroid/manager.py", line 62, in visit_transforms
    return self._transform.visit(node)
  File "~/.virtualenvs/openhtf-local/lib/python2.7/site-packages/astroid/transforms.py", line 83, in visit
    module.body = [self._visit(child) for child in module.body]
  File "~/.virtualenvs/openhtf-local/lib/python2.7/site-packages/astroid/transforms.py", line 53, in _visit
    return self._transform(node)
  File "~/.virtualenvs/openhtf-local/lib/python2.7/site-packages/astroid/transforms.py", line 36, in _transform
    ret = transform_func(node)
  File "openhtf/pylint_plugins/mutablerecords_plugin.py", line 45, in mutable_record_transform
    raise SyntaxError('Invalid mutablerecords syntax')
SyntaxError: Invalid mutablerecords syntax

```

**Comment by fahhem** [comment]
Hmm, not sure why it's even checking for `mutablerecords` when that file doesn't even import that module...
