### ISSUE TITLE
outcome_details not set for aborted phase run from test_start

### ISSUE THREAD

**Issue by DanLipsitt** [google/openhtf#635]
Here's some simplified code that aborts inside a phase run from `test_start`:

```python
import openhtf as htf
from openhtf.output.callbacks import console_summary


@htf.PhaseOptions(repeat_limit=1)
def repeat(test):
    test.test_record.dut_id = '1'
    return htf.PhaseResult.REPEAT

if __name__ == '__main__':
    test = htf.Test()
    test.add_output_callbacks(console_summary.ConsoleSummary())
    test.execute(test_start=repeat)
```

In real life, this would show up if we are trying to get a DUT ID from user input and repeat if it's invalid.

The code triggers a bug when it gets to `ConsoleSummary` (assuming you're running with a version of `ConsoleSummary` that can handle `ABORT`—see #626):

```
2017-08-07 15:51:04,454 - ERROR - Phase returned REPEAT, exceeding repeat_limit.
Finishing test with outcome ABORTED.
Finishing test execution early due to test abortion, outcome ABORTED.
2017-08-07 15:51:04,457 - ERROR - Output callback <openhtf.output.callbacks.console_summary.ConsoleSummary instance at 0x1026d0a28> raised; continuing anyway
Traceback (most recent call last):
  File "/Users/dan/src/shaper/openhtf/openhtf/__init__.py", line 271, in execute
    output_cb(final_state.test_record)
  File "/Users/dan/src/shaper/openhtf/openhtf/output/callbacks/console_summary.py", line 70, in __call__
    (self.indent, record.outcome_details[0].code))
IndexError: list index out of range
```

I have a patch for `ConsoleSummary` that prevents this error, but before I submit it I want to ask whether it makes more sense to fix the underlying issue, which is that `record.outcome_details` isn't being populated.

**Comment by fahhem** [comment]
Hmm, where is this path that gets around `outcome_details`?

**Comment by fahhem** [comment]
I mean, yes, that's probably the right fix.

**Comment by DanLipsitt** [comment]
I think it's because running a phase from `test_start` isn't fully fleshed-out. I haven't done a dive into that part of the code, though.

**Comment by fahhem** [comment]
Yeah :/ `test_start` isn't quite a first-class citizen yet, I wouldn't be surprised if it's funky with this sort of stuff

**Comment by DanLipsitt** [comment]
Can you give me some insight into the intended behavior of `test_start`? It would help me figure out what to do about this and #636. I don't know if I understand the inner workings of openHTF well enough to fix this.

**Comment by fahhem** [comment]
Here's roughly how I view the test start procedure:

* Initialize minimal plugs for first phase
* Run `test_start` phase
* Set test start timestamp
* Initialize all plugs
* Run remaining phases
* Run teardown phase
* Set test stop timestamp

Any step that fails/stops should end the test and set outcome details. If a 'normal' phase (after `test_start`) has failed/stopped, then short-circuit to the teardown phase. We *should* always set the test stop timestamp, no matter why the test failed/stopped/errored.
