### ISSUE TITLE
AttributeError -  test_state.running_phase.attachments.update(self.attachments)

### ISSUE THREAD

**Issue by wallacbe** [google/openhtf#69]
See AttributeError running HTF.  Also seen with example:

Provide a DUT ID in order to start the test.
test
What's the widget type?
asdf

2015-12-05 00:00:31,850 - ERROR - Failed to execute test.
Traceback (most recent call last):
  File "/usr/local/openhtf/openhtf/exe/__init__.py", line 138, in _ThreadProc
    self._ExecuteTest(phase_executor)
  File "/usr/local/openhtf/openhtf/exe/__init__.py", line 164, in _ExecuteTest
    for phase_result in phase_executor.ExecutePhases():
  File "/usr/local/openhtf/openhtf/exe/phasemanager.py", line 150, in ExecutePhases
    result = self._ExecuteOnePhase(self._test_state.pending_phases[0])
  File "/usr/local/openhtf/openhtf/exe/phasemanager.py", line 180, in _ExecuteOnePhase
    result_wrapper.SetResult(phase_thread.JoinOrDie())
  File "/usr/local/venv/local/lib/python2.7/site-packages/contextlib2.py", line 56, in __exit__
    next(self.gen)
  File "/usr/local/openhtf/openhtf/exe/phase_data.py", line 154, in RecordPhaseTiming
    test_state.running_phase.attachments.update(self.attachments)
AttributeError: 'NoneType' object has no attribute 'update'
ERROR:root:Thread raised an exception: Thread-1
Traceback (most recent call last):
  File "/usr/local/openhtf/openhtf/util/threads.py", line 51, in run
    self._ThreadProc()
  File "/usr/local/openhtf/openhtf/exe/__init__.py", line 138, in _ThreadProc
    self._ExecuteTest(phase_executor)
  File "/usr/local/openhtf/openhtf/exe/__init__.py", line 164, in _ExecuteTest
    for phase_result in phase_executor.ExecutePhases():
  File "/usr/local/openhtf/openhtf/exe/phasemanager.py", line 150, in ExecutePhases
    result = self._ExecuteOnePhase(self._test_state.pending_phases[0])
  File "/usr/local/openhtf/openhtf/exe/phasemanager.py", line 180, in _ExecuteOnePhase
    result_wrapper.SetResult(phase_thread.JoinOrDie())
  File "/usr/local/venv/local/lib/python2.7/site-packages/contextlib2.py", line 56, in __exit__
    next(self.gen)
  File "/usr/local/openhtf/openhtf/exe/phase_data.py", line 154, in RecordPhaseTiming
    test_state.running_phase.attachments.update(self.attachments)
AttributeError: 'NoneType' object has no attribute 'update'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/openhtf/openhtf/util/threads.py", line 51, in run
    self._ThreadProc()
  File "/usr/local/openhtf/openhtf/exe/__init__.py", line 138, in _ThreadProc
    self._ExecuteTest(phase_executor)
  File "/usr/local/openhtf/openhtf/exe/__init__.py", line 164, in _ExecuteTest
    for phase_result in phase_executor.ExecutePhases():
  File "/usr/local/openhtf/openhtf/exe/phasemanager.py", line 150, in ExecutePhases
    result = self._ExecuteOnePhase(self._test_state.pending_phases[0])
  File "/usr/local/openhtf/openhtf/exe/phasemanager.py", line 180, in _ExecuteOnePhase
    result_wrapper.SetResult(phase_thread.JoinOrDie())
  File "/usr/local/venv/local/lib/python2.7/site-packages/contextlib2.py", line 56, in __exit__
    next(self.gen)
  File "/usr/local/openhtf/openhtf/exe/phase_data.py", line 154, in RecordPhaseTiming
    test_state.running_phase.attachments.update(self.attachments)
AttributeError: 'NoneType' object has no attribute 'update'

**Comment by jettisonjoe** [comment]
Sorry about that. I should have been more diligent in checking the (seemingly trivial) PR #62, which introduced this regression. I reverted it, so the issue should be fixed. Next attempt to fix the original bug will be tested. Sorry!
