### ISSUE TITLE
module 'openhtf.output.callbacks.mfg_inspector' has no attribute 'MIMETYPE_MAP'

### ISSUE THREAD

**Issue by cyboflash** [google/openhtf#887]
Tried to run frontend_example.py and got the following

```
(master)*$ python3 frontend_example.py
Traceback (most recent call last):
  File "frontend_example.py", line 21, in <module>
    from openhtf.output.servers import station_server
  File "/home/user/projects/myproject/lib/python3.7/site-packages/openhtf/output/servers/station_server.py", line 36, in <module>
    v: k for k, v in six.iteritems(mfg_inspector.MIMETYPE_MAP)
AttributeError: module 'openhtf.output.callbacks.mfg_inspector' has no attribute 'MIMETYPE_MAP'
```

I need to write a GUI for my tests and would be nice to have a working frontend_example.py

**Comment by Minipada** [comment]
I submitted https://github.com/google/openhtf/pull/870 for this but it's been this january maintainers didn't answer. I ended up forking the repo
