### ISSUE TITLE
pandas required by all_the_things.py example

### ISSUE THREAD

**Issue by tcm0116** [google/openhtf#924]
The pandas module is not listed as a standard dependency of the openhtf module, so attempting to run all_the_things.py results in the following error:

```
$ python3 all_the_things.py
Enter a DUT ID in order to start the test.
--> 12345
What's the widget type? (Hint: try `MyWidget` to PASS)
--> MyWidget
Exception in thread monitor_measurement_MonitorThread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/site-packages/openhtf/util/threads.py", line 153, in run
    self._thread_proc()
  File "/usr/lib/python3.8/site-packages/openhtf/core/monitors.py", line 110, in _thread_proc
    time.sleep(start_time - current_time +
openhtf.util.threads.ThreadTerminationError
:ERROR
  exception type: RuntimeError


Error: Install pandas to convert to pandas.DataFrame
```

**Comment by tcm0116** [comment]
Looking into this some more, I can see how it makes sense to not install pandas as part of the default installation. However, it might make sense to add a new extras_requires group for the examples which includes pandas.

**Comment by tcm0116** [comment]
I created pull request #927 to address this issue.
