### ISSUE TITLE
ThreadTerminationError in monitor thread

### ISSUE THREAD

**Issue by tcm0116** [google/openhtf#928]
When a monitor is attached to a phase and that phase ends, the following is displayed on the command line:

```
Exception in thread ps_amps_MonitorThread:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/site-packages/openhtf/util/threads.py", line 153, in run
    self._thread_proc()
  File "/usr/lib/python3.8/site-packages/openhtf/core/monitors.py", line 110, in _thread_proc
    time.sleep(start_time - current_time +
openhtf.util.threads.ThreadTerminationError
```

**Comment by karlp** [comment]
Yep, it's just noise, but it's annoying.
