### ISSUE TITLE
Cambrionix plug: Multiple interface found error

### ISSUE THREAD

**Issue by agdeepak** [google/openhtf#95]
Use case: More than 1 device connected to EtherSync ports.

when test script is invoked, it returns multiple interface found errors. Test script works for only 1 device connected.

2016-01-19 17:30:28,751 - ERROR - Exception instantiating <class 'openhtf.plugs.usb.AdbPlug'> for plug adb:
Traceback (most recent call last):
  File "/home/deepakag/openhtf/venv/local/lib/python2.7/site-packages/openhtf-1.0-py2.7.egg/openhtf/plugs/__init__.py", line 223, in InitializeFromTypes
    plug_map[plug] = plug_type()
  File "/home/deepakag/openhtf/venv/local/lib/python2.7/site-packages/openhtf-1.0-py2.7.egg/openhtf/plugs/usb/__init__.py", line 88, in __new__
    interface_protocol=adb_device.PROTOCOL),
  File "/home/deepakag/openhtf/venv/local/lib/python2.7/site-packages/openhtf-1.0-py2.7.egg/openhtf/plugs/usb/__init__.py", line 58, in _open_usb_handle
    return local_usb.LibUsbHandle.Open(**kwargs)
  File "/home/deepakag/openhtf/venv/local/lib/python2.7/site-packages/openhtf-1.0-py2.7.egg/openhtf/plugs/usb/local_usb.py", line 171, in Open
    raise usb_exceptions.MultipleInterfacesFoundError(kwargs)
MultipleInterfacesFoundError: {'interface_subclass': 66, 'interface_protocol': 1, 'interface_class': 255}
2016-01-19 17:30:28,753 - ERROR - Unable to initialize plugs.
Traceback (most recent call last):
  File "/home/deepakag/openhtf/venv/local/lib/python2.7/site-packages/openhtf-1.0-py2.7.egg/openhtf/exe/__init__.py", line 119, in _RunTestLoop
    plug_manager = self._MakePlugManager(suppressor)
  File "/home/deepakag/openhtf/venv/local/lib/python2.7/site-packages/openhtf-1.0-py2.7.egg/openhtf/exe/__init__.py", line 135, in _MakePlugManager
    self.test.plug_type_map))
  File "/home/deepakag/openhtf/venv/local/lib/python2.7/site-packages/openhtf-1.0-py2.7.egg/openhtf/plugs/__init__.py", line 223, in InitializeFromTypes
    plug_map[plug] = plug_type()
  File "/home/deepakag/openhtf/venv/local/lib/python2.7/site-packages/openhtf-1.0-py2.7.egg/openhtf/plugs/usb/__init__.py", line 88, in __new__
    interface_protocol=adb_device.PROTOCOL),
  File "/home/deepakag/openhtf/venv/local/lib/python2.7/site-packages/openhtf-1.0-py2.7.egg/openhtf/plugs/usb/__init__.py", line 58, in _open_usb_handle
    return local_usb.LibUsbHandle.Open(**kwargs)
  File "/home/deepakag/openhtf/venv/local/lib/python2.7/site-packages/openhtf-1.0-py2.7.egg/openhtf/plugs/usb/local_usb.py", line 171, in Open
    raise usb_exceptions.MultipleInterfacesFoundError(kwargs)
MultipleInterfacesFoundError: {'interface_subclass': 66, 'interface_protocol': 1, 'interface_class': 255}
ERROR:root:Thread raised an exception: Thread-1

**Comment by agdeepak** [comment]
Issue resolved. Debug steps:
Pulled latest Openhtf/Cambrionix plug from Master
Merged changes locally and did setup.py install again in venv
Add esuit64 exe local drive path in cambrionix/__init__.py (def GetUSBSerial --> cmd)
Updated Cambrionix FW 1.10. (FW ver 1.9 does not work with plug)
